package com.atstudio.atstudio.service.storage;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;
import org.springframework.web.multipart.MultipartFile;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;
import java.nio.file.Path;
import java.util.function.Consumer;

@Slf4j
@Service
@RequiredArgsConstructor
public class StorageMutationCoordinator {

    private static final int MAX_ATTEMPTS = 8;

    private final StorageService storageService;
    private final StorageMutationJournalService journalService;
    private final StorageCleanupService cleanupService;

    public String store(
            StorageDomain domain,
            StorageRoot root,
            MultipartFile file,
            String directory) {
        return writeAll(domain, root, List.of(StorageWriteRequest.create(file, directory))).get(0);
    }

    public String replace(
            StorageDomain domain,
            StorageRoot root,
            MultipartFile file,
            String directory,
            String oldKey) {
        return writeAll(domain, root, List.of(StorageWriteRequest.replace(file, directory, oldKey))).get(0);
    }

    public List<String> storeAll(
            StorageDomain domain,
            StorageRoot root,
            List<MultipartFile> files,
            String directory) {
        return writeAll(
                domain,
                root,
                files.stream().map(file -> StorageWriteRequest.create(file, directory)).toList()
        );
    }

    public List<String> writeAll(
            StorageDomain domain,
            StorageRoot root,
            List<StorageWriteRequest> writes) {
        requireTransactionSynchronization();
        if (writes == null || writes.isEmpty()) {
            return List.of();
        }

        String operationId = UUID.randomUUID().toString();
        List<StorageMutationDraft> drafts = writes.stream()
                .map(write -> toDraft(operationId, domain, root, write))
                .toList();

        journalService.registerInFlight(operationId);
        boolean synchronizationRegistered = false;
        try {
            // Own every target durably before any bytes are written, including a failing stage.
            List<Long> mutationIds = journalService.prepare(drafts);
            try {
                for (int index = 0; index < writes.size(); index++) {
                    StorageWriteRequest write = writes.get(index);
                    storageService.stage(root, operationId, drafts.get(index).newKey(), write.file());
                }
                drafts.forEach(draft -> storageService.promote(root, operationId, draft.newKey()));
            } catch (RuntimeException exception) {
                try {
                    cleanupPreparedMutations(mutationIds, drafts);
                } catch (RuntimeException cleanupFailure) {
                    // PREPARED entries remain recoverable even when journal transitions fail.
                    exception.addSuppressed(cleanupFailure);
                }
                throw exception;
            }
            registerSynchronization(mutationIds, drafts);
            synchronizationRegistered = true;
            return drafts.stream().map(StorageMutationDraft::newKey).toList();
        } finally {
            if (!synchronizationRegistered) {
                journalService.releaseInFlight(operationId);
            }
        }
    }

    public void deleteAfterCommit(
            StorageDomain domain,
            StorageRoot root,
            String oldKey) {
        if (oldKey == null || oldKey.isBlank()) {
            return;
        }
        deleteAfterCommit(domain, root, List.of(oldKey));
    }

    /** Own generated bytes without keeping a business transaction open during encoding. */
    public GeneratedWrite generate(StorageDomain domain, StorageRoot root, String directory,
            String filename, Consumer<Path> generator) {
        if (TransactionSynchronizationManager.isActualTransactionActive()) {
            throw new IllegalStateException("Generation must run outside a business transaction");
        }
        String operationId = UUID.randomUUID().toString();
        StorageMutationDraft draft = new StorageMutationDraft(operationId, domain, StorageMutationType.CREATE,
                root, storageService.generateKey(directory, filename), null);
        journalService.registerInFlight(operationId);
        List<Long> ids;
        try {
            ids = journalService.prepare(List.of(draft));
        } catch (RuntimeException exception) {
            journalService.releaseInFlight(operationId);
            throw exception;
        }
        GeneratedWrite generated = new GeneratedWrite(ids, List.of(draft));
        try {
            storageService.stageGenerated(root, operationId, draft.newKey(), generator);
            storageService.promote(root, operationId, draft.newKey());
            return generated;
        } catch (RuntimeException exception) {
            generated.close();
            throw exception;
        }
    }

    public final class GeneratedWrite implements AutoCloseable {
        private final List<Long> ids;
        private final List<StorageMutationDraft> drafts;
        private boolean attached;
        private boolean closed;

        private GeneratedWrite(List<Long> ids, List<StorageMutationDraft> drafts) {
            this.ids = ids;
            this.drafts = drafts;
        }

        public String key() { return drafts.get(0).newKey(); }

        public void attachToTransaction() {
            requireTransactionSynchronization();
            if (attached || closed) throw new IllegalStateException("Generated write already consumed");
            registerSynchronization(ids, drafts);
            attached = true;
        }

        @Override
        public void close() {
            if (attached || closed) return;
            closed = true;
            try {
                runCallbackSafely(drafts.get(0).operationId(), () -> cleanupPreparedMutations(ids, drafts));
            } finally {
                journalService.releaseInFlight(drafts.get(0).operationId());
            }
        }
    }

    public void deleteAfterCommit(
            StorageDomain domain,
            StorageRoot root,
            List<String> oldKeys) {
        requireTransactionSynchronization();
        List<String> keys = oldKeys == null
                ? List.of()
                : oldKeys.stream().filter(key -> key != null && !key.isBlank()).distinct().toList();
        if (keys.isEmpty()) {
            return;
        }
        String operationId = UUID.randomUUID().toString();
        List<StorageMutationDraft> drafts = keys.stream()
                .map(key -> new StorageMutationDraft(
                        operationId,
                        domain,
                        StorageMutationType.DELETE,
                        root,
                        null,
                        key))
                .toList();
        journalService.registerInFlight(operationId);
        boolean synchronizationRegistered = false;
        try {
            List<Long> mutationIds = journalService.prepare(drafts);
            registerSynchronization(mutationIds, drafts);
            synchronizationRegistered = true;
        } finally {
            if (!synchronizationRegistered) {
                journalService.releaseInFlight(operationId);
            }
        }
    }

    private StorageMutationDraft toDraft(
            String operationId,
            StorageDomain domain,
            StorageRoot root,
            StorageWriteRequest write) {
        if (write == null || write.file() == null || write.file().isEmpty()) {
            throw new IllegalArgumentException("A non-empty file is required");
        }
        String newKey = storageService.generateKey(write.directory(), write.file().getOriginalFilename());
        StorageMutationType mutationType = write.oldKey() == null
                ? StorageMutationType.CREATE
                : StorageMutationType.REPLACE;
        return new StorageMutationDraft(
                operationId,
                domain,
                mutationType,
                root,
                newKey,
                write.oldKey()
        );
    }

    private void registerSynchronization(
            List<Long> mutationIds,
            List<StorageMutationDraft> drafts) {
        TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization() {
            @Override
            public void afterCommit() {
                runCallbackSafely(
                        drafts.get(0).operationId(),
                        () -> StorageMutationCoordinator.this.afterCommit(mutationIds, drafts));
            }

            @Override
            public void afterCompletion(int status) {
                try {
                    if (status == STATUS_ROLLED_BACK) {
                        runCallbackSafely(drafts.get(0).operationId(), () -> afterRollback(mutationIds, drafts));
                    }
                } finally {
                    journalService.releaseInFlight(drafts.get(0).operationId());
                }
            }
        });
    }

    private void afterCommit(List<Long> mutationIds, List<StorageMutationDraft> drafts) {
        journalService.transition(mutationIds, StorageMutationState.COMMITTED, "TX_COMMITTED");
        for (int index = 0; index < drafts.size(); index++) {
            Long mutationId = mutationIds.get(index);
            StorageMutationDraft draft = drafts.get(index);
            if (draft.oldKey() == null) {
                journalService.transition(mutationId, StorageMutationState.DONE, "CREATE_COMMITTED");
                continue;
            }
            journalService.transition(
                    mutationId,
                    StorageMutationState.AFTER_COMMIT_DELETE,
                    "OLD_DELETE_PENDING");
            completeOldCleanup(mutationId, draft);
        }
    }

    private void afterRollback(List<Long> mutationIds, List<StorageMutationDraft> drafts) {
        for (int index = 0; index < drafts.size(); index++) {
            Long mutationId = mutationIds.get(index);
            StorageMutationDraft draft = drafts.get(index);
            if (draft.newKey() == null) {
                journalService.transition(mutationId, StorageMutationState.DONE, "TX_ROLLED_BACK_NO_DELETE");
                continue;
            }
            journalService.transition(
                    mutationId,
                    StorageMutationState.ROLLBACK_CLEANUP,
                    "NEW_DELETE_PENDING");
            completeNewCleanup(mutationId, draft);
        }
    }

    private void cleanupPreparedMutations(
            List<Long> mutationIds,
            List<StorageMutationDraft> drafts) {
        for (int index = 0; index < drafts.size(); index++) {
            Long mutationId = mutationIds.get(index);
            StorageMutationDraft draft = drafts.get(index);
            journalService.transition(
                    mutationId,
                    StorageMutationState.ROLLBACK_CLEANUP,
                    "PRE_COMMIT_FAILURE");
            completeNewCleanup(mutationId, draft);
        }
    }

    private void completeNewCleanup(Long mutationId, StorageMutationDraft draft) {
        StorageCleanupService.CleanupOutcome outcome = cleanupService.cleanupNew(
                draft.storageRoot(),
                draft.operationId(),
                draft.newKey());
        if (outcome == StorageCleanupService.CleanupOutcome.DONE) {
            journalService.transition(mutationId, StorageMutationState.DONE, "NEW_DELETE_DONE");
        } else {
            recordRetry(mutationId, "NEW_DELETE_FAILED");
        }
    }

    private void completeOldCleanup(Long mutationId, StorageMutationDraft draft) {
        StorageCleanupService.CleanupOutcome outcome = cleanupService.cleanupOld(
                draft.domain(),
                draft.storageRoot(),
                draft.oldKey());
        switch (outcome) {
            case DONE -> journalService.transition(mutationId, StorageMutationState.DONE, "OLD_DELETE_DONE");
            case SHARED_REFERENCE -> journalService.transition(
                    mutationId,
                    StorageMutationState.DONE,
                    "SHARED_REFERENCE_RETAINED");
            case FAILED -> recordRetry(mutationId, "OLD_DELETE_FAILED");
        }
    }

    private void recordRetry(Long mutationId, String reasonCode) {
        journalService.recordCleanupFailure(
                mutationId,
                reasonCode,
                LocalDateTime.now().plusSeconds(30),
                MAX_ATTEMPTS);
    }

    private void requireTransactionSynchronization() {
        if (!TransactionSynchronizationManager.isSynchronizationActive()) {
            throw new IllegalStateException("Storage mutation requires an active transaction");
        }
    }

    private void runCallbackSafely(String operationId, Runnable callback) {
        try {
            callback.run();
        } catch (RuntimeException exception) {
            log.warn(
                    "Storage mutation callback deferred to recovery. operationId={}, failureType={}",
                    operationId,
                    exception.getClass().getSimpleName());
        }
    }
}
