package com.atstudio.atstudio.entity.enums;

public enum PaymentReconciliationIssueType {
    DONE_ORDER_WITHOUT_PAYMENT,
    ACTIVE_AGREEMENT_WITHOUT_SUBSCRIPTION,
    PROVIDER_DONE_LOCAL_NOT_FINALIZED,
    LOCAL_DONE_PROVIDER_NOT_FOUND,
    LOCAL_DONE_PROVIDER_NOT_DONE,
    AMOUNT_MISMATCH,
    PROVIDER_LOOKUP_FAILED
}
