package com.atstudio.atstudio.entity.enums;

public enum PaymentOperationAuditAction {
    RECONCILIATION_INCIDENT_STATUS_UPDATE,
    RECEIPT_EVIDENCE_CREATED,
    PAYMENT_REFUND_REQUESTED,
    PAYMENT_REFUND_APPROVED,
    PAYMENT_REFUND_PROCESSING,
    PAYMENT_REFUND_SUCCEEDED,
    PAYMENT_REFUND_FAILED,
    PAYMENT_REFUND_PENDING_PROVIDER_CONFIRMATION
}
