import type { WhitelistChannelStatus } from '@/types';

export const ADMIN_STATUS_TRANSITIONS: Record<WhitelistChannelStatus, WhitelistChannelStatus[]> = {
  DRAFT: [],
  PENDING: ['REGISTERED', 'REVISION_REQUESTED', 'REJECTED'],
  EXPORTED: ['REGISTERED', 'REVISION_REQUESTED', 'REJECTED', 'REMOVAL_REQUESTED'],
  REGISTERED: ['REVISION_REQUESTED', 'REMOVAL_REQUESTED'],
  REVISION_REQUESTED: ['REGISTERED', 'REJECTED'],
  REJECTED: [],
  CANCELLED: [],
  REMOVAL_REQUESTED: ['CANCELLED'],
};
